#
#spring.datasource.url=jdbc:mysql://localhost:3306/mybatis_spring_bookstore?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasouce.type=com.alibaba.druid.pool.DruidDataSource
#
#mybatis.configuration.map-underoscore-to-camel-case=true
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis.configuration.lazy-loading-enabled=true
#mybatis.type-aliases-package=com.group13.springbootfirst.entity
##classpath默认到resources中寻找
###mybatis.mapper-locations=classpath:xml/*.xml
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis_spring_bookstore?serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    lazy-loading-enabled: true
#  type-aliases-package: com.group13.springbootfirst.entity
#  mapper-locations: classpath:com/group13/springbootfirst/mapper/xml/*.xml
